import type { Metadata } from "next";
import "./globals.css";
import { LenisProvider } from "@/lib/lenis/lenis";
import { cn } from "@/lib/utils";
import Navbar from "@/components/global/navbar";
import { baseFont, serifFont } from "@/lib/fonts/fonts";
import Footer from "@/components/global/footer";

export const metadata: Metadata = {
   title: "Umrao Cashmere",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={cn("antialiased selection:bg-primary selection:text-white", baseFont.variable, serifFont.variable)}
         >
            <Navbar />
            <LenisProvider>{children}</LenisProvider>
            <Footer />
         </body>
      </html>
   );
}
